// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKq9l4UE87JWCWbo02aFW6BBcGFwqufwo',
    appId: '1:96790747971:web:06ea87ed53a7eacacf6df6',
    messagingSenderId: '96790747971',
    projectId: 'smart-ey-smart-yang-nis',
    authDomain: 'smart-ey-smart-yang-nis.firebaseapp.com',
    storageBucket: 'smart-ey-smart-yang-nis.firebasestorage.app',
  );

  // CORRECT WEB CONFIGURATION FROM YOUR FIREBASE CONSOLE

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMKbyKRZjXHJQc7-RMjbfBdMqcjpN9mQg',
    appId: '1:96790747971:android:4228b137aa124d8ccf6df6',
    messagingSenderId: '96790747971',
    projectId: 'smart-ey-smart-yang-nis',
    storageBucket: 'smart-ey-smart-yang-nis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY_HERE',
    appId: '1:96790747971:ios:06ea87ed53a7eacac6df6',
    messagingSenderId: '96790747971',
    projectId: 'smart-ey-smart-yang-nis',
    storageBucket: 'smart-ey-smart-yang-nis.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfvL1QoC1_4eUyErZ5Js-wa4u3QAyWRdI',
    appId: '1:96790747971:ios:3843f1d098fd671ccf6df6',
    messagingSenderId: '96790747971',
    projectId: 'smart-ey-smart-yang-nis',
    storageBucket: 'smart-ey-smart-yang-nis.firebasestorage.app',
    iosClientId: '96790747971-1i86rc140jmke34l57s0jgu26o4n4mrr.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKq9l4UE87JWCWbo02aFW6BBcGFwqufwo',
    appId: '1:96790747971:web:07debb323d9cf6ffcf6df6',
    messagingSenderId: '96790747971',
    projectId: 'smart-ey-smart-yang-nis',
    authDomain: 'smart-ey-smart-yang-nis.firebaseapp.com',
    storageBucket: 'smart-ey-smart-yang-nis.firebasestorage.app',
  );

}